version: '3.7'

services:
  app_node:
    build:
      context: .
      target: development
    command: 'npx nodemon server/server.js -e json,hbs,html,css,map,jpeg,jpg,png,svg,js'
    ports:
      - '3000:3000'
    volumes:
      - '.:/srv/src'
      - 'node_modules:/srv/src/node_modules'
    depends_on:
      - db_mongo

  db_mongo:
    image: 'mongo:4.2'
    volumes:
      - './mongodb/data:/data/db'
      - './mongodb/etc:/etc/mongo'
    ports:
      - '27017:27017'
    command:
      - mongod

volumes:
  node_modules:
    driver: local
  # mongodb:
  #   driver: local
